const GOT_MESSAGES_FROM_SERVER = 'GOT_MESSAGES_FROM_SERVER';
const DELETE_MESSAGES = 'DELETE_MESSAGES';
const WRITE_MESSAGE = 'WRITE_MESSAGE';
const GOT_NEW_MESSAGE_FROM_SERVER = 'GOT_NEW_MESSAGE_FROM_SERVER';

export {
    GOT_MESSAGES_FROM_SERVER,
    DELETE_MESSAGES,
    WRITE_MESSAGE,
    GOT_NEW_MESSAGE_FROM_SERVER
}